info:
  namespace: blockus
categories:
  blockus:
    enabled: true
    icon: "blockus:rainbow_lamp_on"
    name: 'Blockus'
    permission: "ia.menu.blockus"
    items:
      - "blockus:bamboo_planks"
      - "blockus:charred_planks"
      - "blockus:white_oak_planks"
      - "blockus:acacia_barrel"
      - "blockus:bamboo_barrel"
      - "blockus:birch_barrel"
      - "blockus:charred_barrel"
      - "blockus:crimson_barrel"
      - "blockus:dark_oak_barrel"
      - "blockus:jungle_barrel"
      - "blockus:oak_barrel"
      - "blockus:warped_barrel"
      - "blockus:white_oak_barrel"
      - "blockus:acacia_timber_frame"
      - "blockus:bamboo_timber_frame"
      - "blockus:birch_timber_frame"
      - "blockus:charred_timber_frame"
      - "blockus:crimson_timber_frame"
      - "blockus:dark_oak_timber_frame"
      - "blockus:jungle_timber_frame"
      - "blockus:oak_timber_frame"
      - "blockus:spruce_timber_frame"
      - "blockus:white_oak_timber_frame"
      - "blockus:warped_timber_frame"
      - "blockus:wooden_frame"
      - "blockus:apple_crate"
      - "blockus:beetroot_crate"
      - "blockus:carrot_crate"
      - "blockus:sweet_berries_crate"
      - "blockus:cod_crate"
      - "blockus:golden_apple_crate"
      - "blockus:golden_carrot_crate"
      - "blockus:potato_crate"
      - "blockus:tropical_fish_crate"
      - "blockus:salmon_crate"
      - "blockus:pufferfish_crate"
      - "blockus:acacia_small_logs"
      - "blockus:birch_small_logs"
      - "blockus:crimson_small_stems"
      - "blockus:dark_oak_small_logs"
      - "blockus:jungle_small_logs"
      - "blockus:oak_small_logs"
      - "blockus:spruce_small_logs"
      - "blockus:warped_small_stems"
      - "blockus:white_oak_small_logs"
      - "blockus:blaze_pillar"
      - "blockus:blue_glazed_terracotta_pillar"
      - "blockus:bluestone_pillar"
      - "blockus:brown_glazed_terracotta_pillar"
      - "blockus:charred_nether_pillar"
      - "blockus:cyan_glazed_terracotta_pillar"
      - "blockus:end_stone_pillar"
      - "blockus:gray_glazed_terracotta_pillar"
      - "blockus:green_glazed_terracotta_pillar"
      - "blockus:light_blue_glazed_terracotta_pillar"
      - "blockus:light_gray_glazed_terracotta_pillar"
      - "blockus:lime_glazed_terracotta_pillar"
      - "blockus:limestone_pillar"
      - "blockus:magenta_glazed_terracotta_pillar"
      - "blockus:marble_pillar"
      - "blockus:nether_pillar"
      - "blockus:obsidian_pillar"
      - "blockus:orange_glazed_terracotta_pillar"
      - "blockus:pink_glazed_terracotta_pillar"
      - "blockus:polished_blackstone_pillar"
      - "blockus:polished_diorite_pillar"
      - "blockus:polished_granite_pillar"
      - "blockus:purpleglazedterracottapillar"
      - "blockus:red_glazed_terracotta_pillar"
      - "blockus:red_nether_pillar"
      - "blockus:stone_bricks_pillar"
      - "blockus:teal_nether_pillar"
      - "blockus:white_glazed_terracotta_pillar"
      - "blockus:yellow_glazed_terracotta_pillar"
      - "blockus:beveled_glass"
      - "blockus:black_beveled_glass"
      - "blockus:blue_beveled_glass"
      - "blockus:cyan_beveled_glass"
      - "blockus:gray_beveled_glass"
      - "blockus:green_beveled_glass"
      - "blockus:light_blue_beveled_glass"
      - "blockus:light_gray_beveled_glass"
      - "blockus:lime_beveled_glass"
      - "blockus:magenta_beveled_glass"
      - "blockus:orange_beveled_glass"
      - "blockus:pink_beveled_glass"
      - "blockus:purple_beveled_glass"
      - "blockus:red_beveled_glass"
      - "blockus:white_beveled_glass"
      - "blockus:yellow_beveled_glass"
      - "blockus:asphalt"
      - "blockus:blue_asphalt"
      - "blockus:brown_asphalt"
      - "blockus:cyan_asphalt"
      - "blockus:gray_asphalt"
      - "blockus:green_asphalt"
      - "blockus:light_blue_asphalt"
      - "blockus:light_gray_asphalt"
      - "blockus:lime_asphalt"
      - "blockus:magenta_asphalt"
      - "blockus:orange_asphalt"
      - "blockus:pink_asphalt"
      - "blockus:purple_asphalt"
      - "blockus:red_asphalt"
      - "blockus:white_asphalt"
      - "blockus:yellow_asphalt"
      - "blockus:black_futurneo_block"
      - "blockus:blue_futurneo_block"
      - "blockus:brown_futurneo_block"
      - "blockus:cyan_futurneo_block"
      - "blockus:gray_bright_futurneo_block"
      - "blockus:gray_futurneo_block"
      - "blockus:green_futurneo_block"
      - "blockus:light_blue_futurneo_block"
      - "blockus:light_gray_futurneo_block"
      - "blockus:lime_futurneo_block"
      - "blockus:magenta_futurneo_block"
      - "blockus:orange_futurneo_block"
      - "blockus:pink_futurneo_block"
      - "blockus:purple_futurneo_block"
      - "blockus:red_futurneo_block"
      - "blockus:white_futurneo_block"
      - "blockus:yellow_futurneo_block"
      - "blockus:black_blue_colored_tiles"
      - "blockus:black_gray_colored_tiles"
      - "blockus:black_red_colored_tiles"
      - "blockus:black_white_colored_tiles"
      - "blockus:blue_cyan_colored_tiles"
      - "blockus:bluestone_tiles"
      - "blockus:green_brown_colored_tiles"
      - "blockus:green_orange_colored_tiles"
      - "blockus:light_blue_white_colored_tiles"
      - "blockus:light_blue_yellow_colored_tiles"
      - "blockus:lime_yellow_colored_tiles"
      - "blockus:magenta_black_colored_tiles"
      - "blockus:pink_magenta_colored_tiles"
      - "blockus:purple_orange_colored_tiles"
      - "blockus:purple_blue_colored_tiles"
      - "blockus:red_blue_colored_tiles"
      - "blockus:red_white_colored_tiles"
      - "blockus:zigzagged_andesite"
      - "blockus:zigzagged_bricks"
      - "blockus:zigzagged_charred_nether_bricks"
      - "blockus:zigzagged_diorite"
      - "blockus:zigzagged_end_stone_bricks"
      - "blockus:zigzagged_granite"
      - "blockus:zigzagged_nether_bricks"
      - "blockus:zigzagged_polished_blackstone"
      - "blockus:zigzagged_red_nether_bricks"
      - "blockus:zigzagged_stone_bricks"
      - "blockus:zigzagged_teal_nether_bricks"
      - "blockus:dirt_path1"
      - "blockus:dirt_path2"
      - "blockus:dirt_path3"
      - "blockus:dirt_path4"
      - "blockus:dirt_path5"
      - "blockus:dirt_path6"
      - "blockus:dirt_path7"
      - "blockus:dirt_path8"
      - "blockus:chiseled_andesite_bricks"
      - "blockus:chiseled_bluestone"
      - "blockus:chiseled_diorite_bricks"
      - "blockus:chiseled_end_stone_bricks"
      - "blockus:chiseled_granite_bricks"
      - "blockus:chiseled_limestone"
      - "blockus:chiseled_marble"
      - "blockus:chiseled_marble_pillar"
      - "blockus:chiseled_purpur"
      - "blockus:chiseled_soul_sandstone"
      - "blockus:black_stone_bricks"
      - "blockus:blue_stone_bricks"
      - "blockus:brown_stone_bricks"
      - "blockus:cracked_end_stone_bricks"
      - "blockus:cyan_stone_bricks"
      - "blockus:gray_stone_bricks"
      - "blockus:green_stone_bricks"
      - "blockus:light_blue_stone_bricks"
      - "blockus:lime_stone_bricks"
      - "blockus:magenta_stone_bricks"
      - "blockus:orange_stone_bricks"
      - "blockus:pink_stone_bricks"
      - "blockus:purple_stone_bricks"
      - "blockus:red_stone_bricks"
      - "blockus:white_stone_bricks"
      - "blockus:yellow_stone_bricks"
      - "blockus:andesite_bricks"
      - "blockus:bluestone_bricks"
      - "blockus:bluestone_little_bricks"
      - "blockus:charred_bricks"
      - "blockus:charred_nether_bricks"
      - "blockus:cracked_andesite_bricks"
      - "blockus:cracked_diorite_bricks"
      - "blockus:cracked_granite_bricks"
      - "blockus:crimson_warty_blackstone_bricks"
      - "blockus:diorite_bricks"
      - "blockus:granite_bricks"
      - "blockus:honeycomb_bricks"
      - "blockus:large_bricks"
      - "blockus:limestone_bricks"
      - "blockus:marble_bricks"
      - "blockus:obsidian_bricks"
      - "blockus:purpur_bricks"
      - "blockus:purpur_little_bricks"
      - "blockus:quartz_bricks"
      - "blockus:red_nether_bricks"
      - "blockus:red_sandstone_bricks"
      - "blockus:sandstone_bricks"
      - "blockus:sandy_bricks"
      - "blockus:small_red_sandstone_bricks"
      - "blockus:small_sandstone_bricks"
      - "blockus:small_soul_sandstone_bricks"
      - "blockus:smooth_charred_nether_bricks"
      - "blockus:smooth_nether_bricks"
      - "blockus:smooth_red_nether_bricks"
      - "blockus:smooth_teal_nether_bricks"
      - "blockus:soaked_bricks"
      - "blockus:soul_sandstone_bricks"
      - "blockus:teal_nether_bricks"
      - "blockus:warped_warty_blackstone_bricks"
      - "blockus:andesite_circle_pavement"
      - "blockus:diorite_circle_pavement"
      - "blockus:granite_circle_pavement"
      - "blockus:limestone_circle_pavement"
      - "blockus:marble_circle_pavement"
      - "blockus:netherrack_circle_pavement"
      - "blockus:obsidian_circle_pavement"
      - "blockus:polished_blackstone_circle_pavement"
      - "blockus:prismarine_circle_pavement"
      - "blockus:quartz_circle_pavement"
      - "blockus:stone_circle_pavement"
      - "blockus:black_shingles"
      - "blockus:blue_shingles"
      - "blockus:brown_shingles"
      - "blockus:cyan_shingles"
      - "blockus:green_shingles"
      - "blockus:light_blue_shingles"
      - "blockus:light_gray_shingles"
      - "blockus:lime_shingles"
      - "blockus:magenta_shingles"
      - "blockus:orange_shingles"
      - "blockus:pink_shingles"
      - "blockus:purple_shingles"
      - "blockus:red_shingles"
      - "blockus:white_shingles"
      - "blockus:yellow_shingles"
      - "blockus:shingles"
      - "blockus:blue_redstone_lamp_on"
      - "blockus:brown_redstone_lamp_on"
      - "blockus:cyan_redstone_lamp_on"
      - "blockus:gray_redstone_lamp_on"
      - "blockus:green_redstone_lamp_on"
      - "blockus:light_blue_redstone_lamp_on"
      - "blockus:light_gray_redstone_lamp_on"
      - "blockus:lime_redstone_lamp_on"
      - "blockus:magenta_redstone_lamp_on"
      - "blockus:orange_redstone_lamp_on"
      - "blockus:pink_redstone_lamp_on"
      - "blockus:purple_redstone_lamp_on"
      - "blockus:red_redstone_lamp_on"
      - "blockus:white_redstone_lamp_on"
      - "blockus:yellow_redstone_lamp_on"
      - "blockus:soul_o_lantern"
      - "blockus:blaze_block"
      - "blockus:bluestone"
      - "blockus:bluestone_lines"
      - "blockus:bluestone_squares"
      - "blockus:burned_paper_block"
      - "blockus:caution_block"
      - "blockus:companion_cube"
      - "blockus:cookie_block"
      - "blockus:cut_soul_sandstone"
      - "blockus:ender_block"
      - "blockus:iron_plating"
      - "blockus:limestone"
      - "blockus:love_block"
      - "blockus:marble"
      - "blockus:membrane_block"
      - "blockus:paper_block"
      - "blockus:paper_wall"
      - "blockus:polished_end_stone"
      - "blockus:polished_netherrack"
      - "blockus:purpur_lines"
      - "blockus:purpur_squares"
      - "blockus:redstone_sand"
      - "blockus:road_barrier"
      - "blockus:rotten_flesh_block"
      - "blockus:smooth_bluestone"
      - "blockus:smoothpurpur"
      - "blockus:sugar_block"
      - "blockus:thatch"
      - "blockus:weight_storage_cube"
      - "blockus:white_oak_leaves"
      - "blockus:bread_box"
      - "blockus:chorus_block"
      - "blockus:soul_sandstone"
      - "blockus:stripped_white_oak_log"
      - "blockus:white_oak_log"
      - "blockus:chiseled_lava_bricks"
      - "blockus:chiseled_lava_polished_blackstone"
      - "blockus:lava_bricks"
      - "blockus:lava_polished_blackstone_bricks"
      - "blockus:magma_bricks"
      - "blockus:chiseled_water_bricks"
      - "blockus:water_bricks"
      - "blockus:nether_stars_block"
      - "blockus:rainbow_block"
      - "blockus:rainbow_bricks"
      - "blockus:rainbow_colored_tiles"
      - "blockus:rainbow_lamp_on"
      - "blockus:soul_lantern_block"
      - "blockus:lantern_block"
      - "blockus:stars_block"